### ISSUE TITLE
PyPI page not rendering properly

### ISSUE THREAD

**Issue by msabramo** [nextoa/comb#1]
Probably some minor reST problem. 

See https://bitbucket.org/pypa/pypi/issue/161/rest-formatting-fails-and-there-is-no-way

**Comment by 9nix00** [comment]
Hi,@msabramo
Thanks for your reminder,I was too busy missing the message. the document error is fixed.
[https://pypi.python.org/pypi/comb](https://pypi.python.org/pypi/comb)
