### ISSUE TITLE
[Suggestion] Change magic method `__enter__`, `__exit__` to contextlib

### ISSUE THREAD

**Issue by HerringtonDarkholme** [nextoa/comb#2]
`contextlib` or its clone is more pythonic and provides more concise api. Magic methods can be spared for library users.

https://docs.python.org/3.4/library/contextlib.html#module-contextlib

Here we need three methods to define, with the power of contextlib these could be refactored into two. A `slot` method and a `arrange_slot` method.

**Comment by 9nix00** [comment]
Hi,@HerringtonDarkholme

Thanks your suggestion, and you are right. I will change it in future.

**Comment by 9nix00** [comment]
Hi,@HerringtonDarkholme

These days I have time to review my code.  `contextlib.ContextDecorator` is I want. but it's a new feature on python3.4.

I need support python2 & python3. 

it hard to say use `contextlib.decorators` is pythonic or not. our purpose is help user to finish his business code easier. class maybe a better way.

FYI, recently, I reviewed some small projects of mime and plan refactored them. 
I migrated this project into `cliez`.  you can see this demo at https://github.com/9nix00/cliez/tree/master/demo/slot_demo/slot_pkg

Thanks your suggestion again.
